### ISSUE TITLE
Use enum_flags for scoped enumerations used as bitmask flags.

### ISSUE THREAD

**Issue by lumik** [lumik/sprelay#6]
Use general template based concept for bitmask implementation through scoped enumerations utilizing [enum_flags](https://github.com/lumik/enum_flags) library.

**Comment by peterkubascik** [comment]
I would like to use private variable of type unsigned char called Stack, which will represent selected relays. At the beginning will be Stack initialized to RelayID::None. Class K8090 will also dispose by public methods Add, which will sign other relays to Stack and resetStack which reset into original state.

**Comment by lumik** [comment]
Why? Each command takes relays to be affected as a parameter. Why not use enumeration as flags for desired relays. It is more transparent then some unsigned chars or arrays. Each command then would take `RelayID` parameter with desired relays. It is possible, that if we use it in slots, we have to register `RelayID` enumeration in Qts metaobject system, see http://doc.qt.io/qt-5/custom-types.html.

By the way - I suppose to rename `RelayID` to `RealyIDs`, which better describes, that it can contain more values at once and the enumerators should be capitalized according to our styleguide (i.e. ONE, TWO, etc.).
