### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by peterkubascik** [lumik/sprelay#8]
Another way how to solve problem with choosing relays. Branch Stack don't have to be merged it's just alternative solution.

**Comment by lumik** [comment]
I think, that this class should only implement the functionality of the Relay card. If you want it to remember the particular relay in use, implement base class with raw relay functionality at first and then develop improvements in derived class. But I think, it is not necessary, the controlling program should controll all relays like program shipped with the relay card driver.

**Comment by lumik** [comment]
Why the name `stack`, stack is used to store thinks and then pop them out. It should be named `used_relays_` or somethink like that (note underscore at the end, which should be there for private variables according to our style guide).

**Comment by peterkubascik** [comment]
Yes, now I understand. I will just push it to repo to save ideas, later if we don't need it, we will delete it. I also changed names.

**Comment by lumik** [comment]
What is the problem with header safeguards? Cpplint should treat them correctly because it treated them correctly in `develop` branch where they are the same.

**Comment by peterkubascik** [comment]
I used cpplint and i get this 

![cpplint](https://user-images.githubusercontent.com/26647589/29459123-878e7814-8422-11e7-91b3-76f1efa9ed2d.JPG)

**Comment by lumik** [comment]
Which version of cpplint do you use? Use the one distributed with the project - go to the directory containing the project and use command
```
python lib/cpplint-1.3.0/cpplint.py --recursive src tests
```
to test the whole repository.
You can find this command at the last line of the `.travis.yml` file which manages automated tests on Travis CI.
